### ISSUE TITLE
[Bug]: Unable to import plugin netbox-secrets: Module not found.

### ISSUE THREAD

**Issue by cmcknz77** [Onemind-Services-LLC/netbox-secrets#120]
### NetBox Secrets plugin version

v1.10.0

### NetBox version

v3.7.0

### Steps to Reproduce

(venv) [root@localhost netbox]# python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-3.7.0/netbox/netbox/settings.py", line 748, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox-secrets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox-3.7.0/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 103, in wrapper
    saved_locale = translation.get_language()
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.7.0/netbox/netbox/settings.py", line 751, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox-secrets: Module not found. Check that the plugin module has been installed within the correct Python environment.

### Expected Behavior

python3 manage.py migrate succeeds

### Observed Behavior

![Screenshot 2024-01-03 005705](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/8886905/599d4243-7c64-46f8-929c-b86505e675d9)
![Screenshot 2024-01-03 012400](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/8886905/436d620c-4662-4e19-be67-ec88b564b70a)

![Screenshot 2024-01-03 005849](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/8886905/b1168046-a98a-479b-887e-f519704a8a60)

**Comment by cmcknz77** [comment]
Sorry - this was an ID: 10T error... I'd used a - instead of a _ in the configuration.
