### ISSUE TITLE
[Bug]: ImproperlyConfigured: Application labels aren't unique, duplicates

### ISSUE THREAD

**Issue by lukassavukaitis** [Onemind-Services-LLC/netbox-secrets#160]
### NetBox Secrets plugin version

v2.0.3

### NetBox version

v4.1.1

### Steps to Reproduce

I'm getting this error when running migrations after installing this plugin:

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: netbox_topology_views

```

### Expected Behavior

Migrations should run successfully

### Observed Behavior

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: netbox_topology_views

```

**Comment by kirk444** [comment]
AFAIK this is not yet compatible with 4.1.x, so you may have to go back to 4.0.x until that is ready.

**Comment by abhi1693** [comment]
Your issue is with another plugin. Please raise the issue with netbox community

**Comment by FontouraAbreu** [comment]
@lukassavukaitis or for anyone else facing the same problem:

You should try and rebuild your docker image since if you're using Docker. As your `requirements.txt` will be reinstalled and then properly installing your new plugin

if you're not using docker you should just `pip install -r requiments.txt` :)
