### ISSUE TITLE
[Bug]: Plugin netbox_secrets requires NetBox minimum version 4.1.0 (current: 4.0.11)

### ISSUE THREAD

**Issue by gignat88** [Onemind-Services-LLC/netbox-secrets#167]
### NetBox Secrets plugin version

v2.0.3

### NetBox version

4.0.11

### Steps to Reproduce

Trying to install netbox-secrets plugin v 2.0.3 and got errors  :

i am running ./upgrade script and this is the error : 

Successfully installed drf-extra-fields-3.7.0 filetype-1.2.0 **netbox-documents-0.7.0 netbox-floorplan-plugin-0.4.1 netbox-secrets-2.1.0 netbox-topology-views-4.1.0** pycryptodome-3.21.0
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/base.py", line 104, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/utils/translation/__init__.py", line 211, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/utils/translation/__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 829, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/opt/netbox/netbox/netbox/plugins/__init__.py", line 140, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_secrets requires NetBox minimum version 4.1.0 (current: 4.0.11).

i have installed topology, documents and floorplan plugins and they work .

i have downloaded versione 2.03 :  

(venv) netbox@netbox:/opt/netbox$ pip show netbox-secrets
Name: netbox-secrets
Version: 2.0.3
Summary: Enhance your secret management with encrypted storage and flexible, user-friendly features.
Home-page: https://github.com/Onemind-Services-LLC/netbox-secrets/
Author: Abhimanyu Saharan
Author-email: asaharan@onemindservices.com
License: Apache 2.0
Location: /opt/netbox/venv/lib/python3.12/site-packages
Requires: pycryptodome
Required-by:

i am using netbox (v4.0.11)

if you can guide me , i will be grateful

### Expected Behavior

i was expected to install the plugin as it did for the previous 3 plugins

### Observed Behavior

got the above errors

**Comment by abhi1693** [comment]
You have installed version 2.1.0 instead as per your log.
